import { test, expect } from '@playwright/test'

test('staff management, station schedule and reservation filters work in the browser', async ({ page }) => {
  const password = process.env.VERIFICATION_PASSWORD
  if (!password) throw new Error('Run through tests/verify_api.py --browser against its disposable API.')
  await page.goto('/')
  await page.getByLabel('Email or NIC').fill('backoffice@solar.local')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Enter workspace' }).click()
  await expect(page.getByRole('heading', { name: /Welcome/ })).toBeVisible()
  await page.screenshot({ path: '../artifacts/screenshots/01-dashboard.png', fullPage: true })

  await page.getByRole('button', { name: 'People & access' }).click()
  await page.getByRole('button', { name: 'Add prosumer', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add prosumer' })
  await dialog.getByLabel('NIC', { exact: true }).fill('888888888V')
  await dialog.getByLabel('Full name').fill('Browser Test Prosumer')
  await dialog.getByLabel('Email', { exact: true }).fill('browser@example.test')
  await dialog.getByLabel('Phone').fill('+94771234568')
  await dialog.getByLabel('Address').fill('Browser verification address')
  await dialog.getByLabel('Initial password').fill(password)
  await dialog.getByRole('button', { name: 'Save account' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByLabel('Search', { exact: true }).fill('888888888V')
  await expect(page.getByText('Browser Test Prosumer', { exact: true })).toBeVisible()
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Activate', exact: true }).click()
  await page.getByLabel('Search', { exact: true }).fill('888888888V')
  await expect(page.locator('.person-row .status')).toHaveText('Active')
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Full name').fill('Updated Browser Prosumer')
  await page.getByRole('button', { name: 'Save account' }).click()
  await expect(page.getByText('Updated Browser Prosumer', { exact: true })).toBeVisible()
  await page.screenshot({ path: '../artifacts/screenshots/02-people.png', fullPage: true })

  await page.getByRole('button', { name: 'Solar stations', exact: true }).click()
  await page.getByPlaceholder('Search stations…').fill('Updated Hub')
  await page.getByRole('button', { name: 'Manage station & slots' }).click()
  const management = page.getByRole('dialog', { name: 'Station & schedule', exact: true })
  await expect(management.getByLabel('Name', { exact: true })).toHaveValue('Updated Hub')
  await management.getByLabel('Operating hours').fill('07:00-20:00')
  await management.getByRole('button', { name: 'Save station', exact: true }).click()
  await expect(management.getByText('Saved successfully.')).toBeVisible()
  await management.getByRole('button', { name: 'Add slot', exact: true }).click()
  const slotDialog = page.getByRole('dialog', { name: 'Create slot', exact: true })
  const local = (hours: number) => { const d = new Date(Date.now() + hours * 3600000); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
  await slotDialog.getByLabel('Start (local time)').fill(local(96))
  await slotDialog.getByLabel('End (local time)').fill(local(97))
  await slotDialog.getByLabel('Capacity').fill('5')
  await slotDialog.getByRole('button', { name: 'Save slot' }).click()
  await expect(slotDialog).not.toBeVisible()
  await expect(management.getByText('Slot saved successfully.')).toBeVisible()
  await page.screenshot({ path: '../artifacts/screenshots/03-station-slots.png', fullPage: true })
  await management.getByRole('button', { name: 'Close', exact: true }).click()

  await page.getByRole('button', { name: 'Reservations', exact: true }).click()
  await page.getByRole('button', { name: 'New reservation' }).click()
  await page.getByLabel('Prosumer', { exact: true }).selectOption({ label: 'Updated Browser Prosumer / 888888888V' })
  await page.getByLabel('Solar station', { exact: true }).selectOption({ label: 'Updated Hub / Test address' })
  await expect(page.getByLabel('Available slot')).toBeEnabled()
  const options = await page.getByLabel('Available slot').locator('option').allTextContents()
  await page.getByLabel('Available slot').selectOption({ label: options.find((v) => v.includes('0/5 reserved'))! })
  await page.getByLabel('Energy amount (kWh)').fill('7')
  await page.getByRole('button', { name: 'Create reservation', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Choose your moment.' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Pending', exact: true }).click()
  await page.getByLabel('Search', { exact: true }).fill('888888888V')
  await expect(page.locator('.table-row')).toHaveCount(1)
  await expect(page.locator('.table-row')).toContainText('7 kWh')
  await page.screenshot({ path: '../artifacts/screenshots/04-reservations.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '../artifacts/screenshots/05-responsive.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
